EXPERIMENT:
  NAME: ""
  TAG: "NormKD_W_DKD,res50,mobilenetv1"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "NormKD_W_DKD"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV1"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
NormKD_W_DKD:
  CE_WEIGHT: 1.0
  ALPHA: 1.0
  BETA: 1.0
  TEMPERATURE_NORM: 0.75
  WARMUP: 1
