EXPERIMENT:
  NAME: ""
  TAG: "NormKD_W_DKD,wrn_40_2,shuv1"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "NormKD_W_DKD"
  TEACHER: "wrn_40_2"
  STUDENT: "ShuffleV1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
NormKD_W_DKD:
    ALPHA: 4.0
    BETA: 5.0